### ISSUE TITLE
Question with docNade

### ISSUE THREAD

**Issue by Waateur** [huashiyiqike/TMBP#1]
Hello,
I know the implementation of Docnade may not be yours. 
But I'm having some difficulty to extract words probability out of it and you maybe know the solution. 
I have trained a few models using docNade network. But know I want to use it to predict the next words of a sentences. 
I use the fprob function on word_ids and words in my document and  I though that " _self.probs_ " would give me the probability of  words in the document. But instead It gave me **17** list of probabilities and I do not understand what this **17** is.  I search through the paper [http://arxiv.org/pdf/1603.05962.pdf]( http://arxiv.org/pdf/1603.05962.pdf) but didn't find any clues about it. 
Do you have any infos that might help me ? 

Thank you in advance for your time.

**Comment by huashiyiqike** [comment]
sorry but I cannot help you. Best wishes
